package com.assist.transacciones.bancarias.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.assist.transacciones.bancarias.dto.UsuarioDto;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Transacciones")
public class Transacciones {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String idTransaccion;
    @DynamoDBAttribute
    private String tipo;
    @DynamoDBAttribute
    private String valor;
    @DynamoDBAttribute
    private String origen;
    @DynamoDBAttribute
    private String idCuenta;
    @DynamoDBAttribute
    private String usuario;
}
